### PR TITLE
Fixes an issue with the user page looking bad on small screens.

### PR DESCRIPTION
**Pull request by gdpotter**
/domain @hirefrank 

The .pull-right class caused the .col-md-3 to keep its width the size of
the image within, causing it to look really really bad on small (mobile)
screens. I've replaced the .pull-right with just a basic .col-md-3 but
used the "push" and "pull" classes to put the box on top on small screens
but on the right on large screens.

Note: I haven't tested this (I don't know how to run it...so maybe check my code first)

### CODE REVIEW

**Comment by hirefrank** [comment]
@gdpotter 

I've deployed it here for testing: 
https://12-dot-bettersnippets.appspot.com/user/frank.harris@betterment.com

Let me know if this looks right.

Btw, if you want to be a contributor, let me know. Thanks!

**Comment by gdpotter** [comment]
Yup! It looks good to me.

**Comment by hirefrank** [comment]
Uh oh... 

screen shot 2016-07-12 at 11 09 50 am

**Comment by gdpotter** [comment]
Oops, I had a typo. I fixed the commit.

**Pull request merged**
